name = "AssortiveMatingABM"
uuid = "e4da7c70-dfd9-4073-ad5e-fd5bb5e7460e"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Agents = "6.2.1"
Distributions = "0.25.115"
Random = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
